In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import chi2,f_classif
import re
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
# players = pd.read_csv(r"Datasets\world_cup\WorldCupPlayers.csv")
matches = pd.read_csv(r"Datasets\world_cup\WorldCupMatches.csv")
all_players = pd.read_csv(r"Datasets\world_cup\all_players.csv") 
squad = pd.read_csv(r"Datasets\world_cup\2018_squad.csv")


In [3]:
matches.drop_duplicates(inplace=True)
matches.Year.value_counts(sort=False)
matches.Attendance.fillna( np.max(matches[(matches.Year == 2014) & (matches.Stadium == 'Estadio Beira-Rio')].dropna().Attendance), inplace=True )

In [121]:
squad.columns

Index(['Team', 'Group', 'Squad Number', 'Position', 'Player', 'Date Of Birth',
       'Age', 'Caps', 'Goals', 'Club', 'Player Count'],
      dtype='object')

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

In [4]:
def wdl(x):
    if x['Home Team Goals'] > x['Away Team Goals']:
        return "Win"
    elif x['Home Team Goals']< x['Away Team Goals']:
        return "Loss"
    elif x['Home Team Goals'] == x['Away Team Goals']:
        return "Draw"
matches["Result"] = matches.apply(wdl,axis=1)

Based on the values found below , we can say that a team has never lost after scoring three goals and have always won a mathch when they score 4+ goals. Out of 59 cases there are 2 cases when a team has drawn after scoring 4 goals. 
A team cant win if they havent scored any goal. therefore to take number of goals as a feature we are choosing 1,2,3 number of goals as a feature to predict team win or loss or draw.


In [5]:
matches[matches["Result"]=="Win"]['Home Team Goals'].value_counts(sort=False)
matches[matches["Result"]=="Draw"]['Home Team Goals'].value_counts(sort=False)
matches[matches["Result"]=="Loss"]['Home Team Goals'].value_counts(sort=False)
matches['Home Team Goals'].value_counts(sort=False)

matches["Goal_1"]=matches['Home Team Goals'].apply(lambda x: 1 if x == 1 else 0)
matches["Goal_2"]=matches['Home Team Goals'].apply(lambda x: 1 if x == 2 else 1)
matches["Goal_3"]=matches['Home Team Goals'].apply(lambda x: 1 if x == 3 else 1)


In [223]:
matches["ml"]

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials',
       'Result', 'Goal_1', 'Goal_2', 'Goal_3'],
      dtype='object')

C:\Users\tgup1\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([255.1463813]), array([3.67753661e-87]))

In [6]:
matches.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials',
       'Result', 'Goal_1', 'Goal_2', 'Goal_3'],
      dtype='object')

In [ ]:
# X = np.array(matches['Home Team Goals']).reshape(-1,1)
# y = np.array(matches['Result']).reshape(-1,1)
# # # chi2(X,y)
# # f_classif(X,y)
from sklearn.preprocessing import MultiLabelBinarizer


Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials',
       'Result', 'Goal_1', 'Goal_2', 'Goal_3'],
      dtype='object')

In [55]:
matches.columns


Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials',
       'Result', 'Goal_1', 'Goal_2', 'Goal_3'],
      dtype='object')

In [71]:
X=matches[matches["Home Team Name"]=="England"][["Home Team Goals","Attendance","Half-time Home Goals","Half-time Away Goals"]]
y = matches[matches["Home Team Name"]=="England"]["Result"]


array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [72]:
y = [[x] for x in y]
binarizer = MultiLabelBinarizer()
y = binarizer.fit_transform(y)
binarizer.classes_


array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [91]:
# model = SVC()
# model.fit(X,y)
# model.score(X,y)


ValueError: bad input shape (35, 3)

In [87]:
rf = RandomForestClassifier(n_estimators=10)
rf.fit(X,y)
rf.score(X,y)


array([[1., 0., 0.]])

array([[1., 0., 0.]])

In [90]:
rf.predict(np.array(['4',"14257","3","1"]).reshape(1,-1))


array([[1., 0., 0.]])

In [3]:
all_players.columns

Index(['Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential',
       'Club', 'Club Logo', 'Value', 'Wage', 'Special', 'Acceleration',
       'Aggression', 'Agility', 'Balance', 'Ball Control', 'Composure',
       'Crossing', 'Curve', 'Dribbling', 'FK Accuracy', 'Finishing',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Heading Accuracy', 'Interceptions', 'Jumping',
       'Long Passing', 'Long Shots', 'Marking', 'Penalties', 'Positioning',
       'Reactions', 'Short Passing', 'Shot Power', 'Sliding Tackle',
       'Sprint Speed', 'Stamina', 'Standing Tackle', 'Strength', 'Vision',
       'Volleys'],
      dtype='object')

In [4]:
all_players.shape

(18000, 46)

In [39]:
df=all_players.set_index("Nationality")
temp=df.sort_index().groupby("Nationality")
x=temp.count()
x = x[x["Name"]>20]
# countries with more than 20 players 
x.index

Index(['Albania', 'Algeria', 'Argentina', 'Australia', 'Austria', 'Belgium',
       'Bolivia', 'Bosnia Herzegovina', 'Brazil', 'Bulgaria', 'Cameroon',
       'Canada', 'Cape Verde', 'Chile', 'China PR', 'Colombia', 'Congo',
       'Costa Rica', 'Croatia', 'Czech Republic', 'DR Congo', 'Denmark',
       'Ecuador', 'Egypt', 'England', 'Finland', 'France', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Guinea', 'Hungary', 'Iceland', 'India',
       'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Korea Republic', 'Kosovo',
       'Mali', 'Mexico', 'Montenegro', 'Morocco', 'Netherlands', 'New Zealand',
       'Nigeria', 'Northern Ireland', 'Norway', 'Paraguay', 'Peru', 'Poland',
       'Portugal', 'Republic of Ireland', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Senegal', 'Serbia', 'Slovakia', 'Slovenia', 'South Africa',
       'Spain', 'Sweden', 'Switzerland', 'Tunisia', 'Turkey', 'Ukraine',
       'United States', 'Uruguay', 'Venezuela', 'Wales'],
      dtype='object', name='

In [49]:
all_players.shape

(18000, 46)

In [40]:
all_players.columns

Index(['Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential',
       'Club', 'Club Logo', 'Value', 'Wage', 'Special', 'Acceleration',
       'Aggression', 'Agility', 'Balance', 'Ball Control', 'Composure',
       'Crossing', 'Curve', 'Dribbling', 'FK Accuracy', 'Finishing',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Heading Accuracy', 'Interceptions', 'Jumping',
       'Long Passing', 'Long Shots', 'Marking', 'Penalties', 'Positioning',
       'Reactions', 'Short Passing', 'Shot Power', 'Sliding Tackle',
       'Sprint Speed', 'Stamina', 'Standing Tackle', 'Strength', 'Vision',
       'Volleys'],
      dtype='object')

In [93]:
# these are the countries with more than 20 players in their roster
countries = ['Albania', 'Algeria', 'Argentina', 'Australia', 'Austria', 'Belgium',
       'Bolivia', 'Bosnia Herzegovina', 'Brazil', 'Bulgaria', 'Cameroon',
       'Canada', 'Cape Verde', 'Chile', 'China PR', 'Colombia', 'Congo',
       'Costa Rica', 'Croatia', 'Czech Republic', 'DR Congo', 'Denmark',
       'Ecuador', 'Egypt', 'England', 'Finland', 'France', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Guinea', 'Hungary', 'Iceland', 'India',
       'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Korea Republic', 'Kosovo',
       'Mali', 'Mexico', 'Montenegro', 'Morocco', 'Netherlands', 'New Zealand',
       'Nigeria', 'Northern Ireland', 'Norway', 'Paraguay', 'Peru', 'Poland',
       'Portugal', 'Republic of Ireland', 'Romania', 'Russia', 'Saudi Arabia',
       'Scotland', 'Senegal', 'Serbia', 'Slovakia', 'Slovenia', 'South Africa',
       'Spain', 'Sweden', 'Switzerland', 'Tunisia', 'Turkey', 'Ukraine',
       'United States', 'Uruguay', 'Venezuela', 'Wales']
all_players=all_players[all_players.apply(lambda x: x["Nationality"] in countries,axis=1)]

In [94]:

def name_convertor(names):
    new_names = []
    for x in names:
        name=x.split(" ")
        if len(name)> 1:
            first_name = name[0][0]+"."
            name[0]=first_name
        new_names.append(" ".join(name))
    return new_names


In [115]:
# take user input 
team_name = "Croatia"
whole_team = all_players[all_players["Nationality"]== team_name].drop_duplicates()
whole_team = whole_team.dropna()
players = squad[squad["Team"]== team_name]
players["Player"]=players["Player"].apply(lambda x:re.sub("\(\w+\)","",x).strip())
players["Name"] = name_convertor(players["Player"])
final_squad = pd.merge(whole_team,players,on=["Name"],how='inner')


C:\Users\tgup1\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\tgup1\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


In [120]:
# final_squad[["Player","Club_y","Position"]]
final_squad.columns

Index(['Name', 'Age_x', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential',
       'Club_x', 'Club Logo', 'Value', 'Wage', 'Special', 'Acceleration',
       'Aggression', 'Agility', 'Balance', 'Ball Control', 'Composure',
       'Crossing', 'Curve', 'Dribbling', 'FK Accuracy', 'Finishing',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Heading Accuracy', 'Interceptions', 'Jumping',
       'Long Passing', 'Long Shots', 'Marking', 'Penalties', 'Positioning',
       'Reactions', 'Short Passing', 'Shot Power', 'Sliding Tackle',
       'Sprint Speed', 'Stamina', 'Standing Tackle', 'Strength', 'Vision',
       'Volleys', 'Team', 'Group', 'Squad Number', 'Position', 'Player',
       'Date Of Birth', 'Age_y', 'Caps', 'Goals', 'Club_y', 'Player Count'],
      dtype='object')

In [119]:
all_players[all_players["Name"]=="B. Pavard"].iloc[:,:4]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Name</th>
      <th>Age</th>
      <th>Photo</th>
      <th>Nationality</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>973</th>
      <td>B. Pavard</td>
      <td>21</td>
      <td>https://cdn.sofifa.org/sm/18/players/226851.png</td>
      <td>France</td>
    </tr>
  </tbody>
</table>
</div>

368              Alisson
369         Thiago Silva
370              Miranda
371        Pedro Geromel
372             Casemiro
373          Filipe Luís
374        Douglas Costa
375       Renato Augusto
376        Gabriel Jesus
377               Neymar
378    Philippe Coutinho
379              Marcelo
380           Marquinhos
381               Danilo
382             Paulinho
383               Cássio
384          Fernandinho
385                 Fred
386              Willian
387      Roberto Firmino
388               Taison
389               Fagner
390              Ederson
Name: Player, dtype: object
['Alisson', 'T. Silva', 'Miranda', 'P. Geromel', 'Casemiro', 'F. Luís', 'D. Costa', 'R. Augusto', 'G. Jesus', 'Neymar', 'P. Coutinho', 'Marcelo', 'Marquinhos', 'Danilo', 'Paulinho', 'Cássio', 'Fernandinho', 'Fred', 'Willian', 'R. Firmino', 'Taison', 'Fagner', 'Ederson']


C:\Users\tgup1\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\tgup1\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [176]:
final_squad[]

368              Alisson
369         Thiago Silva
370              Miranda
371        Pedro Geromel
372             Casemiro
373          Filipe Luís
374        Douglas Costa
375       Renato Augusto
376        Gabriel Jesus
377               Neymar
378    Philippe Coutinho
379              Marcelo
380           Marquinhos
381               Danilo
382             Paulinho
383               Cássio
384          Fernandinho
385                 Fred
386              Willian
387      Roberto Firmino
388               Taison
389               Fagner
390              Ederson
Name: Player, dtype: object
['Alisson', 'T. Silva', 'Miranda', 'P. Geromel', 'Casemiro', 'F. Luís', 'D. Costa', 'R. Augusto', 'G. Jesus', 'Neymar', 'P. Coutinho', 'Marcelo', 'Marquinhos', 'Danilo', 'Paulinho', 'Cássio', 'Fernandinho', 'Fred', 'Willian', 'R. Firmino', 'Taison', 'Fagner', 'Ederson']


C:\Users\tgup1\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\tgup1\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Player</th>
      <th>Club_y</th>
      <th>Position</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Harry Kane</td>
      <td>Tottenham Hotspur</td>
      <td>FW</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Harry Kane</td>
      <td>Tottenham Hotspur</td>
      <td>FW</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Raheem Sterling</td>
      <td>Manchester City</td>
      <td>FW</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Dele Alli</td>
      <td>Tottenham Hotspur</td>
      <td>MF</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Kyle Walker</td>
      <td>Manchester City</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Jamie Vardy</td>
      <td>Leicester City</td>
      <td>FW</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Gary Cahill</td>
      <td>Chelsea</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Marcus Rashford</td>
      <td>Manchester United</td>
      <td>FW</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Jesse Lingard</td>
      <td>Manchester United</td>
      <td>MF</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Jack Butland</td>
      <td>Stoke City</td>
      <td>GK</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Eric Dier</td>
      <td>Tottenham Hotspur</td>
      <td>MF</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Jordan Henderson</td>
      <td>Liverpool</td>
      <td>MF</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Danny Rose</td>
      <td>Tottenham Hotspur</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Danny Rose</td>
      <td>Tottenham Hotspur</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Danny Rose</td>
      <td>Tottenham Hotspur</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Jordan Pickford</td>
      <td>Everton</td>
      <td>GK</td>
    </tr>
    <tr>
      <th>16</th>
      <td>John Stones</td>
      <td>Manchester City</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Phil Jones</td>
      <td>Manchester United</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>18</th>
      <td>Phil Jones</td>
      <td>Manchester United</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>19</th>
      <td>Kieran Trippier</td>
      <td>Tottenham Hotspur</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>20</th>
      <td>Harry Maguire</td>
      <td>Leicester City</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Danny Welbeck</td>
      <td>Arsenal</td>
      <td>FW</td>
    </tr>
    <tr>
      <th>22</th>
      <td>Fabian Delph</td>
      <td>Manchester City</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>23</th>
      <td>Ashley Young</td>
      <td>Manchester United</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>24</th>
      <td>Nick Pope</td>
      <td>Burnley</td>
      <td>GK</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Trent Alexander-Arnold</td>
      <td>Liverpool</td>
      <td>DF</td>
    </tr>
    <tr>
      <th>26</th>
      <td>Ruben Loftus-Cheek</td>
      <td>Crystal Palace</td>
      <td>MF</td>
    </tr>
  </tbody>
</table>
</div>

In [165]:
final_squad.columns

Index(['Name', 'Age_x', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential',
       'Club_x', 'Club Logo', 'Value', 'Wage', 'Special', 'Acceleration',
       'Aggression', 'Agility', 'Balance', 'Ball Control', 'Composure',
       'Crossing', 'Curve', 'Dribbling', 'FK Accuracy', 'Finishing',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Heading Accuracy', 'Interceptions', 'Jumping',
       'Long Passing', 'Long Shots', 'Marking', 'Penalties', 'Positioning',
       'Reactions', 'Short Passing', 'Shot Power', 'Sliding Tackle',
       'Sprint Speed', 'Stamina', 'Standing Tackle', 'Strength', 'Vision',
       'Volleys', 'Team', 'Group', 'Squad Number', 'Position', 'Player',
       'Date Of Birth', 'Age_y', 'Caps', 'Goals', 'Club_y', 'Player Count'],
      dtype='object')

In [69]:
squad["Team"].value_counts()

Uruguay         23
Tunisia         23
Brazil          23
Japan           23
Poland          23
Croatia         23
Russia          23
Australia       23
Mexico          23
Switzerland     23
Peru            23
England         23
Argentina       23
Spain           23
Denmark         23
Saudi Arabia    23
Iran            23
Sweden          23
South Korea     23
Morocco         23
Iceland         23
France          23
Costa Rica      23
Nigeria         23
Germany         23
Egypt           23
Colombia        23
Portugal        23
Belgium         23
Serbia          23
Senegal         23
Panama          23
Name: Team, dtype: int64

In [187]:
whole_team = all_players[all_players["Nationality"]== team_name]

In [200]:
len(whole_team)

152

In [205]:
temp=whole_team.dropna()
temp.columns

Index(['Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential',
       'Club', 'Club Logo', 'Value', 'Wage', 'Special', 'Acceleration',
       'Aggression', 'Agility', 'Balance', 'Ball Control', 'Composure',
       'Crossing', 'Curve', 'Dribbling', 'FK Accuracy', 'Finishing',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Heading Accuracy', 'Interceptions', 'Jumping',
       'Long Passing', 'Long Shots', 'Marking', 'Penalties', 'Positioning',
       'Reactions', 'Short Passing', 'Shot Power', 'Sliding Tackle',
       'Sprint Speed', 'Stamina', 'Standing Tackle', 'Strength', 'Vision',
       'Volleys'],
      dtype='object')

In [192]:
len(final_squad)

23